// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD7mLbI6kPiQBywe-pHi6PZGTMJj71ujY',
    appId: '1:107697055599:web:915a1989d9aaba875c6a9a',
    messagingSenderId: '107697055599',
    projectId: 'expense-tracker-2996e',
    authDomain: 'expense-tracker-2996e.firebaseapp.com',
    storageBucket: 'expense-tracker-2996e.firebasestorage.app',
    measurementId: 'G-FDGM84LEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGndVluInMXM8QL_8o6cis7nCyE07iU_c',
    appId: '1:107697055599:android:74700c493979da425c6a9a',
    messagingSenderId: '107697055599',
    projectId: 'expense-tracker-2996e',
    storageBucket: 'expense-tracker-2996e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQcU2CszU2Hos4_YD9RukcnM_E3awexc',
    appId: '1:107697055599:ios:598164916a0f54485c6a9a',
    messagingSenderId: '107697055599',
    projectId: 'expense-tracker-2996e',
    storageBucket: 'expense-tracker-2996e.firebasestorage.app',
    iosBundleId: 'com.example.eTrackerUpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQcU2CszU2Hos4_YD9RukcnM_E3awexc',
    appId: '1:107697055599:ios:598164916a0f54485c6a9a',
    messagingSenderId: '107697055599',
    projectId: 'expense-tracker-2996e',
    storageBucket: 'expense-tracker-2996e.firebasestorage.app',
    iosBundleId: 'com.example.eTrackerUpi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD7mLbI6kPiQBywe-pHi6PZGTMJj71ujY',
    appId: '1:107697055599:web:9f76133866c3db5d5c6a9a',
    messagingSenderId: '107697055599',
    projectId: 'expense-tracker-2996e',
    authDomain: 'expense-tracker-2996e.firebaseapp.com',
    storageBucket: 'expense-tracker-2996e.firebasestorage.app',
    measurementId: 'G-HT8GJE1D57',
  );
}
